# Codemagic iOS Build Configuration
# Free Tier: 500 minutes/month for macOS builds

workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        BUNDLE_ID: "com.tarottimer.app"
        XCODE_WORKSPACE: "ios/TarotTimer.xcworkspace"
        XCODE_SCHEME: "TarotTimer"
      node: 20.11.0
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true

    scripts:
      - name: 📦 Install npm dependencies
        script: |
          npm ci

      - name: 🔧 Install Expo CLI
        script: |
          npm install -g expo-cli eas-cli

      - name: 📱 Prebuild iOS project
        script: |
          npx expo prebuild --platform ios --clean

      - name: 📦 Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: 🔍 Find iOS workspace
        script: |
          echo "📂 Checking iOS directory structure..."
          ls -la ios/

          # Find the actual workspace file
          WORKSPACE_FILE=$(find ios -name "*.xcworkspace" -type d | head -n 1)
          echo "✅ Found workspace: $WORKSPACE_FILE"

          # Find the scheme name
          SCHEME_NAME=$(xcodebuild -workspace "$WORKSPACE_FILE" -list | grep -A 1 "Schemes:" | tail -n 1 | xargs)
          echo "✅ Found scheme: $SCHEME_NAME"

          # Export for next step
          echo "WORKSPACE_FILE=$WORKSPACE_FILE" >> $CM_ENV
          echo "SCHEME_NAME=$SCHEME_NAME" >> $CM_ENV

      - name: 📝 Create export options plist
        script: |
          cat > $CM_BUILD_DIR/export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>teamID</key>
              <string>YOUR_TEAM_ID</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF
          echo "✅ Created export_options.plist"
          cat $CM_BUILD_DIR/export_options.plist

      - name: 🏗️ Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$WORKSPACE_FILE" \
            --scheme "$SCHEME_NAME" \
            --config "Release" \
            --export-options-plist "$CM_BUILD_DIR/export_options.plist"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - changsekwon@gmail.com
        notify:
          success: true
          failure: true
